### ISSUE TITLE
quic transport

### ISSUE THREAD

**Issue by progrium** [progrium/qtalk-go#2]
implement quic transport based on https://github.com/lucas-clemente/quic-go

ideally it wouldn't be a dependency, maybe it would work as a submodule? or a separate repo?

otherwise, the API and general semantics of using quic are nearly identical to qmux in the mux package. a wrapper will probably be needed to fit the interfaces expected. this would be an alternative transport, so it would register itself in `talk` as a dialer. probably as "quic".

**Comment by mgood** [comment]
Based on the current API, the QUIC dialer would also need to return a `*Session`, which expects a `ReadWriteCloser` as the input. So AFAICT even though QUIC could support multiple streams, in order to provide a ReadWriteCloser interface, I would basically just be wrapping a single QUIC Stream, and then qmux would still be responsible for managing channels.
Or did you have in mind implementing an interface around `Session` with the semantics more directly mapped to the QUIC protocol?

**Comment by progrium** [comment]
I think the idea was to treat `*Session` like an interface (we can define one) and make qmux one implementation of the "qtalk session layer" and quic be another. So just pretend Session and Channel are interfaces and the Session interface are the exported methods of `*mux.Session`. This means the `rpc` package will have to work against the interfaces now, but it was designed like that so it should mostly be there.

We could also put this off for now (it's not a priority just would be nice to finally have), esp since I wanted to re-org stuff a little, which might as well involve transitioning to interfaces for Session and Channel. Then this would be more straightforward.
