### ISSUE TITLE
rpc: support multiple return values in unary calls

### ISSUE THREAD

**Issue by progrium** [progrium/qtalk-go#25]
Although you can send back multiple values when implementing a handler directly, this requires using Continue so the calling side stays open after it receives the first value. It also means the calling side must use Receive on the response value instead of just the reply argument of Call. 

This issue would change Call to support multiple reply values. Instead of passing a reference to a single value, it would check for an `[]any`, and specifically one in which the first element is a reference (to not confuse with a return reply value for a slice of strings, for example). Errors will continue to come back as the error for Call and not be included in this. I'm not sure the responding side needs to do anything extra other than return multiple values (no new fields to CallHeader), but Call would not close the connection until all reply values are set. The responder on the handler side would need to let you return multiple values in the Return call, as well as the Continue call (which is a return, plus potentially more values). 

Totally optional, but for convenience/readability, a `fn.Return` type can be made similar to `fn.Args`. However, this shouldn't be required since code in `rpc` shouldn't depend on `fn`. In other words, this can't be used to check for multiple return values in the Call arguments.

**Comment by mgood** [comment]
So, to verify, this would take an argument like this to pass references to the multiple return values:
```
var a int
var b float64
c.Call(ctx, "foo", nil, []any{&a, &b})
```

Or how would you feel about a variadic `Call` to pass each return as an argument, e.g.:
```
var a int
var b float64
c.Call(ctx, "foo", nil, &a, &b)
```
That simplifies the calling code a little as well.

However, I think for the case you mentioned about distinguishing expecting a single slice as the return, in that case the caller would be expected to pass a pointer to a slice like this in order to decode the values, right?
```
var s []string
c.Call(ctx, "foo", nil, &s)
```

**Comment by progrium** [comment]
Yes, you got it. And a variadic Call seems like it should be fine. And yes that's what it would look like to get a string slice return value.
