### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by progrium** [progrium/qtalk-go#6]
* [ ] traditional unary rpc, exporting methods
* [ ] streaming results, handler interface
* [ ] byte stream proxy 
* [ ] reverse role rpc, server calling client function
* [ ] state sync via callback

put examples in wiki, link to and make video for readme

**Comment by riscdanger** [comment]
I implemented the first one as a simple cli tool that echos a backwards message. Let me know if there's some other pattern for examples that I should use. I'm going to do streaming rpc next.

**Comment by riscdanger** [comment]
I've been thinking more about this since your feedback on my PR. What do you think about an `examples` package that's a basic command line tool with a single server implementation and multiple clients for each command? They can share some code with each other. Also, the godocs could be added to make it a higher level user guide, even using Go Example functions. 

Is there some qtalk-typescript package somewhere? In the future, the command line tool could be adapted into a backend server for an HTML file that visualizes the various communication patterns.

I want to focus on implementing the commands and organizing the code to fit this idea in my PR, so I finish this week. How's that sound?

**Comment by progrium** [comment]
progrium/qtalk-js for the TS/browser implementation. 

this is interesting though. so you're talking about a command daemon that is basically just a hub. commands can be run as separate programs that connect to it to provide commands. and then a CLI tool connects to the hub to run commands. this seems a little contrived but i think does show some of the strengths in an understandable way.

**Comment by progrium** [comment]
i was already thinking of an eventual `qtalk` command that was a generic CLI client for working with qtalk endpoints useful for debugging and bootstrapping projects/ideas. it could even run in a listen mode and respond to calls running shell scripts in the working directory.

**Comment by riscdanger** [comment]
That's even cooler! Maybe these examples stay really simple, and I'll take notes for a `qtalk` command for a future release. 

I still think merging them into one package could be helpful, with output something like this:

```sh
$ go run _examples/main.go [example-name]
[bi-directional rpc]
... terminal output ...

[streaming rpc]
... terminal output ...

...
```

**Comment by riscdanger** [comment]
```
$ go run _examples/*.go callbacks
[callbacks]
echo: hello.
>>> abc
send:  abc
echo:  cba

$ go run _examples/*.go rpc
[rpc]
echo: hello.
>>> test
send:  test
worker 1: sel "md5", job "tset" // 122.458µs
worker 2: sel "sha1", job "tset" // 32.75µs
worker 3: sel "sha256", job "tset" // 27.834µs
<< echo:    tset
 < md5:     751ec45015a704a39dc403001c963e97
 < sha1:    6e45a996ca8c1c3bb0a7807c039dfffb02c0cad2
 < sha256:  18ea285983df355f3024e412fb46ad6cbd98a7ffe6872e26612e35f38aa39c41
```

I have a first pass with client peers pushing their calls to a queue of workers.

**Comment by progrium** [comment]
I think we can evolve your code into the CLI client idea, I'm going to do more tutorial style examples on the wiki with a video demo.
